using System;

internal enum Enum2
{
    SUCCESS,
    OPEN_DEVICE_FAILED,
    FIND_DEVICE_FAILED,
    INVALID_PARAMETER,
    INVALID_BLOCK_NUMBER,
    HARDWARE_COMMUNICATE_ERROR,
    INVALID_PASSWORD,
    ACCESS_DENIED,
    ALREADY_OPENED,
    ALLOCATE_MEMORY_FAILED,
    INVALID_UPDATE_PACKAGE,
    SYN_ERROR,
    OTHER_ERROR
}

